// BITE.co Frontend Configuration — auto-generated by Terraform
// Do NOT edit this file manually; edit frontend/config.js.tpl instead.
const CONFIG = {
  AUTH_URL:     'http://${alb_dns}',
  USUARIOS_URL: 'http://${alb_dns}',
  CLOUD_URL:    'http://${alb_dns}',
  REPORTES_URL: 'http://${alb_dns}',
  SEGURIDAD_URL:'http://${alb_dns}',
};
